@extends('layouts.panel')

@section('page_title', 'Record Retention')
@section('page_desc', 'Review five-year retention deadlines and manage auditable legal holds.')

@section('content')
@php
    $activeStatus = request('status');
    $statusLabels = ['retained' => 'Retained', 'pending_disposal_review' => 'Pending review', 'legal_hold' => 'Legal hold'];
@endphp
<style>
.retention-page{width:min(100%,1640px);margin:auto;padding:clamp(.6rem,1.5vw,1.25rem) clamp(1rem,2.4vw,2.25rem) 2rem;color:var(--color-text-primary)}.retention-page *{min-width:0}.retention-stack{display:grid;gap:1rem}.retention-hero{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.05rem 1.15rem;border:1px solid #b8c7b1;border-radius:16px;background:linear-gradient(135deg,#dce9d8,#edf1e4)}
.retention-hero-copy{display:flex;align-items:center;gap:.8rem}.retention-icon{display:grid;place-items:center;width:44px;height:44px;flex:0 0 auto;border-radius:12px;background:#fff9;color:#315f43;font-size:1.15rem}.retention-hero h1,.retention-panel h2{margin:0;font-family:var(--font-heading)}.retention-hero h1{font-size:clamp(1.25rem,2vw,1.7rem)}.retention-hero p,.retention-panel p{margin:.2rem 0 0;color:var(--color-text-secondary);font-size:.78rem}.policy-chip{display:flex;align-items:center;gap:.45rem;padding:.55rem .75rem;border:1px solid #a5b99e;border-radius:10px;background:#d0e1cd;color:#315f43;font-size:.7rem;font-weight:850;white-space:nowrap}
.retention-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem}.retention-metric{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:.7rem;min-height:92px;padding:.82rem;border:1px solid #c5d0bf;border-radius:14px;background:#e4ecdf;color:inherit;text-decoration:none}.retention-metric:nth-child(2){background:#eee3cf}.retention-metric:nth-child(3){background:#eadbd3}.retention-metric:nth-child(4){background:#e8e7d7}.retention-metric:hover,.retention-metric:focus-visible{transform:translateY(-1px);border-color:#315f43;outline:2px solid #315f4326;outline-offset:2px}.retention-metric>i:first-child{display:grid;place-items:center;width:36px;height:36px;border-radius:10px;background:#fff8;color:#315f43}.retention-metric span{display:block;color:var(--color-text-secondary);font-size:.61rem;font-weight:800;text-transform:uppercase}.retention-metric strong{display:block;font:700 1.35rem var(--font-heading)}.retention-metric .bi-chevron-right{font-size:.65rem}
.retention-alert{display:flex;gap:.6rem;align-items:flex-start;padding:.75rem .85rem;border:1px solid;border-radius:11px;font-size:.7rem;line-height:1.45}.retention-alert.policy{background:#f2e6c8;border-color:#d9bc7b;color:#694a1d}.retention-alert.success{background:#d6e7d3;border-color:#a8c4a3;color:#285d3e}.retention-alert.error{background:#efd7d1;border-color:#d5aaa1;color:#853c34}.retention-alert ul{margin:0;padding-left:1rem}
.retention-toolbar{display:flex;align-items:center;justify-content:space-between;gap:.75rem;flex-wrap:wrap;padding:.75rem;border:1px solid #bdcbb7;border-radius:13px;background:#dde8d8}.retention-toolbar-copy strong{display:block;font-size:.75rem}.retention-toolbar-copy span{color:var(--color-text-secondary);font-size:.61rem}.retention-filters{display:flex;align-items:center;gap:.4rem;flex-wrap:wrap}.retention-filter{display:inline-flex;align-items:center;gap:.35rem;min-height:36px;padding:.45rem .62rem;border:1px solid #a9b9a3;border-radius:8px;background:#eef3e9;color:#465847;font-size:.61rem;font-weight:850;text-decoration:none}.retention-filter:hover,.retention-filter:focus-visible,.retention-filter.active{border-color:#315f43;background:#315f43;color:#fff;outline:none}
.retention-panel{overflow:hidden;border:1px solid #c4d0be;border-radius:16px;background:#e3eddf}.retention-panel-head{display:flex;align-items:center;justify-content:space-between;gap:.7rem;padding:.85rem 1rem;border-bottom:1px solid #788a7429}.retention-panel-title{display:flex;align-items:center;gap:.6rem}.retention-panel-title .retention-icon{width:34px;height:34px;font-size:.9rem}.retention-panel h2{font-size:.94rem}.result-count{padding:.28rem .48rem;border-radius:999px;background:#cddfc9;color:#315f43;font-size:.58rem;font-weight:850}.retention-table-wrap{overflow-x:auto}.retention-table{width:100%;min-width:900px;border-collapse:collapse}.retention-table th{padding:.72rem .8rem;background:#d3dfce;color:#526158;font-size:.58rem;text-align:left;text-transform:uppercase;letter-spacing:.08em}.retention-table td{padding:.75rem .8rem;border-top:1px solid #becbb8;font-size:.7rem;vertical-align:middle}.retention-table tbody tr:hover td{background:#d9e6d5}.case-code{font-weight:900;color:#315f43}.case-sub{display:block;color:var(--color-text-secondary);font-size:.58rem}.status-pill{display:inline-flex;align-items:center;gap:.3rem;padding:.28rem .48rem;border-radius:999px;font-size:.58rem;font-weight:850}.status-pill.retained{background:#cce1c9;color:#285d3e}.status-pill.pending_disposal_review{background:#f0dfbc;color:#75521f}.status-pill.legal_hold{background:#efd0ca;color:#923d34}
.hold-state{display:grid;gap:.45rem}.hold-copy{display:flex;gap:.4rem;color:#853c34;font-size:.62rem;line-height:1.4}.hold-form{display:grid;grid-template-columns:minmax(180px,1fr) auto;gap:.4rem}.hold-input{width:100%;min-height:36px!important;padding:.42rem .55rem!important;border:1px solid #aebda8!important;border-radius:8px!important;background:#f5f7f1!important;font-size:.62rem!important}.hold-button{display:inline-flex;align-items:center;justify-content:center;gap:.3rem;min-height:36px;padding:.42rem .58rem;border:1px solid #315f43;border-radius:8px;background:#315f43;color:#fff;font-size:.6rem;font-weight:850;white-space:nowrap;cursor:pointer}.hold-button.release{border-color:#a66a30;background:#f0dfbc;color:#754c1e}.hold-button:hover,.hold-button:focus-visible{filter:brightness(.93);outline:2px solid #315f4326;outline-offset:1px}.retention-empty{padding:3rem 1rem;text-align:center;color:var(--color-text-secondary)}.retention-empty i{display:block;margin-bottom:.5rem;font-size:1.55rem;color:#71816e}.retention-empty strong{display:block;color:var(--color-text-primary);font-size:.82rem}.retention-pagination{padding:.7rem .85rem;border-top:1px solid #bdcab7;background:#d8e3d3}
@media(max-width:1050px){.retention-metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.retention-page{padding:.6rem .75rem 1.5rem}.retention-hero{align-items:flex-start;flex-direction:column}.policy-chip{white-space:normal}.retention-metrics{grid-template-columns:1fr}.retention-filters{width:100%}.retention-filter{flex:1;justify-content:center}.hold-form{grid-template-columns:1fr}}
</style>

<div class="retention-page retention-stack animate-float-up">
    <header class="retention-hero"><div class="retention-hero-copy"><button type="button" id="mobileSidebarToggle" class="mobile-menu-btn" aria-label="Open navigation" aria-expanded="false" aria-controls="appSidebar"><i class="bi bi-list"></i></button><span class="retention-icon"><i class="bi bi-hourglass-split"></i></span><div><h1>Record Retention</h1><p>Five-year retention monitoring and legal-hold governance across all branches.</p></div></div><div class="policy-chip"><i class="bi bi-shield-lock"></i>Review-only disposal policy</div></header>

    @if(session('success'))<div class="retention-alert success" role="status"><i class="bi bi-check-circle-fill"></i><strong>{{ session('success') }}</strong></div>@endif
    @if($errors->any())<div class="retention-alert error" role="alert"><i class="bi bi-exclamation-circle-fill"></i><div><strong>The legal-hold request could not be completed:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif

    <section class="retention-metrics" aria-label="Retention overview">
        <a class="retention-metric" href="{{ route('admin.retention.index') }}"><i class="bi bi-calendar3"></i><div><span>Due within 90 days</span><strong>{{ $counts['due_90'] }}</strong></div><i class="bi bi-chevron-right"></i></a>
        <a class="retention-metric" href="{{ route('admin.retention.index') }}"><i class="bi bi-alarm"></i><div><span>Due within 30 days</span><strong>{{ $counts['due_30'] }}</strong></div><i class="bi bi-chevron-right"></i></a>
        <a class="retention-metric" href="{{ route('admin.retention.index', ['status' => 'pending_disposal_review']) }}"><i class="bi bi-clipboard-check"></i><div><span>Pending review</span><strong>{{ $counts['pending'] }}</strong></div><i class="bi bi-chevron-right"></i></a>
        <a class="retention-metric" href="{{ route('admin.retention.index', ['status' => 'legal_hold']) }}"><i class="bi bi-lock"></i><div><span>Legal hold</span><strong>{{ $counts['legal_hold'] }}</strong></div><i class="bi bi-chevron-right"></i></a>
    </section>

    <div class="retention-alert policy"><i class="bi bi-info-circle-fill"></i><div><strong>Controlled retention safeguard</strong><br>Permanent disposal remains disabled until the funeral home's five-year policy and legal/accounting requirements are formally approved. Eligible records are queued for review only.</div></div>

    <nav class="retention-toolbar" aria-label="Retention filters"><div class="retention-toolbar-copy"><strong>Retention register</strong><span>Filter records by their current governance status.</span></div><div class="retention-filters">
        <a class="retention-filter {{ !$activeStatus ? 'active' : '' }}" href="{{ route('admin.retention.index') }}"><i class="bi bi-grid"></i>All</a>
        @foreach($statusLabels as $value => $label)<a class="retention-filter {{ $activeStatus === $value ? 'active' : '' }}" href="{{ route('admin.retention.index', ['status' => $value]) }}">{{ $label }}</a>@endforeach
    </div></nav>

    <section class="retention-panel"><header class="retention-panel-head"><div class="retention-panel-title"><span class="retention-icon"><i class="bi bi-archive"></i></span><div><h2>{{ $activeStatus ? ($statusLabels[$activeStatus] ?? 'Filtered').' records' : 'All retained records' }}</h2><p>Completion dates, deadlines, status, and hold controls.</p></div></div><span class="result-count">{{ $cases->total() }} {{ \Illuminate\Support\Str::plural('record', $cases->total()) }}</span></header>
        <div class="retention-table-wrap"><table class="retention-table"><thead><tr><th>Case</th><th>Branch</th><th>Completed</th><th>Retention ends</th><th>Status</th><th>Legal hold</th></tr></thead><tbody>
        @forelse($cases as $case)
            <tr><td><span class="case-code">{{ $case->case_code }}</span>@if($case->deceased)<span class="case-sub">{{ $case->deceased->full_name ?? trim(($case->deceased->first_name ?? '').' '.($case->deceased->last_name ?? '')) }}</span>@endif</td><td>{{ $case->branch?->branch_code ?? 'Unassigned' }}</td><td>{{ $case->completed_at?->format('M d, Y') ?? '—' }}</td><td><strong>{{ $case->retention_end_date?->format('M d, Y') ?? '—' }}</strong></td><td><span class="status-pill {{ $case->retention_status }}"><i class="bi {{ $case->retention_status === 'legal_hold' ? 'bi-lock-fill' : ($case->retention_status === 'pending_disposal_review' ? 'bi-hourglass-bottom' : 'bi-shield-check') }}"></i>{{ $statusLabels[$case->retention_status] ?? \Illuminate\Support\Str::headline($case->retention_status) }}</span></td><td>
                @if($case->legal_hold_at)<div class="hold-state"><div class="hold-copy"><i class="bi bi-lock-fill"></i><span><strong>Held {{ $case->legal_hold_at->format('M d, Y') }}</strong><br>{{ $case->legal_hold_reason }}</span></div><form method="POST" action="{{ route('admin.retention.release-hold', $case) }}" class="hold-form" data-submit-lock>@csrf<label class="sr-only" for="release-reason-{{ $case->id }}">Reason for releasing legal hold</label><input id="release-reason-{{ $case->id }}" name="reason" required minlength="10" placeholder="Release reason (minimum 10 characters)" class="hold-input"><button type="submit" class="hold-button release"><i class="bi bi-unlock"></i><span>Release</span></button></form></div>
                @else<form method="POST" action="{{ route('admin.retention.place-hold', $case) }}" class="hold-form" data-submit-lock>@csrf<label class="sr-only" for="hold-reason-{{ $case->id }}">Legal hold reason</label><input id="hold-reason-{{ $case->id }}" name="reason" required minlength="10" placeholder="Legal hold reason (minimum 10 characters)" class="hold-input"><button type="submit" class="hold-button"><i class="bi bi-lock"></i><span>Place hold</span></button></form>@endif
            </td></tr>
        @empty
            <tr><td colspan="6"><div class="retention-empty"><i class="bi bi-archive"></i><strong>No records in this view</strong><span>{{ $activeStatus ? 'Try another status filter.' : 'Completed cases with retention dates will appear here.' }}</span></div></td></tr>
        @endforelse
        </tbody></table></div><div class="retention-pagination">{{ $cases->links() }}</div>
    </section>
</div>
<script>
document.querySelectorAll('[data-submit-lock]').forEach((form)=>form.addEventListener('submit',()=>{const button=form.querySelector('button[type="submit"]');if(!button)return;button.disabled=true;button.setAttribute('aria-busy','true');const label=button.querySelector('span');if(label)label.textContent='Processing…';}));
</script>
@endsection
