<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportTitle }} - Print</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 12mm;
            @bottom-center {
                content: "Generated by Sabangan Caguioa Funeral Home Management System";
                font-size: 8.5px;
                color: #5F685F;
            }
            @bottom-right {
                content: "Page " counter(page);
                font-size: 8.5px;
                color: #5F685F;
            }
        }
        * { box-sizing: border-box; }
        body { margin: 0; background: #e5e7eb; color: #111827; font-family: Arial, Helvetica, sans-serif; line-height: 1.35; }
        .sheet { max-width: 1320px; min-height: 100vh; margin: 0 auto; background: #fff; padding: 28px 30px 34px; }
        .print-actions { display: flex; justify-content: flex-end; gap: 8px; margin-bottom: 16px; }
        .btn { border: 1px solid #9ca3af; background: #fff; color: #111827; border-radius: 8px; padding: 9px 14px; cursor: pointer; font-weight: 700; }
        .btn-primary { background: #111827; color: #fff; border-color: #111827; }
        .report-head {
            display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 28px; align-items: center;
            border-bottom: 2px solid #111827; padding-bottom: 16px;
        }
        .brand { display: flex; gap: 14px; align-items: center; min-width: 0; }
        .brand-logo {
            width: 52px; height: 52px; border: 2px solid #111827; border-radius: 4px; display: grid; place-items: center;
            background: #fff; flex: 0 0 auto; padding: 4px;
        }
        .brand-logo img {
            width: 100%; height: 100%; object-fit: contain; display: block;
        }
        .brand h1 { margin: 0; font-size: 24px; letter-spacing: 0; line-height: 1.12; }
        .brand p { margin: 4px 0 0; font-size: 12px; color: #374151; font-weight: 700; }
        .meta {
            text-align: right; font-size: 11px; border: 1px solid #d1d5db; background: #f9fafb;
            padding: 9px 11px; min-width: 238px;
        }
        .meta p { margin: 3px 0; color: #374151; }
        .report-title { margin: 16px 0 10px; display: flex; justify-content: space-between; gap: 18px; align-items: flex-end; }
        .report-title h2 { margin: 0; font-size: 19px; line-height: 1.2; }
        .report-title p { margin: 4px 0 0; color: #5F685F; font-size: 11px; }
        .section-label {
            margin: 0 0 7px; color: #374151; font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: .06em;
        }
        .filters-block { margin: 0 0 13px; break-inside: avoid; }
        .filters { display: flex; flex-wrap: wrap; gap: 6px; }
        .filter {
            border: 1px solid #C9C5BB; background: #FAFAF7; border-radius: 999px; padding: 5px 9px;
            font-size: 10.5px; color: #111827;
        }
        .filter strong { color: #374151; }
        .summary-block { margin: 0 0 14px; break-inside: avoid; }
        .summary-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 7px; }
        .summary-card { border: 1px solid #C9C5BB; background: #fff; padding: 8px 9px; min-height: 50px; break-inside: avoid; }
        .summary-card span { display: block; font-size: 9.5px; color: #5F685F; text-transform: uppercase; font-weight: 800; letter-spacing: .03em; }
        .summary-card strong { display: block; margin-top: 4px; font-size: 14.5px; color: #111827; font-variant-numeric: tabular-nums; }
        .table-wrap { width: 100%; overflow: visible; }
        .report-table { width: 100%; border-collapse: collapse; table-layout: auto; border: 1px solid #9ca3af; }
        .report-table th, .report-table td { border: 1px solid #C9C5BB; padding: 6px 7px; text-align: left; font-size: 10px; vertical-align: top; }
        .report-table th {
            background: #f3f4f6; color: #111827; font-size: 9.5px; font-weight: 800;
            letter-spacing: 0; text-transform: none;
        }
        .report-table tbody tr:nth-child(even) td { background: #fcfcfd; }
        .report-table tr { break-inside: avoid; page-break-inside: avoid; }
        .number { text-align: right !important; white-space: nowrap; font-variant-numeric: tabular-nums; }
        .empty { text-align: center; color: #5F685F; padding: 20px !important; }
        .signatures { display: grid; grid-template-columns: 1fr 1fr; gap: 82px; margin-top: 42px; break-inside: avoid; page-break-inside: avoid; }
        .signature-box { text-align: center; }
        .signature-label { margin-bottom: 28px; font-size: 12px; font-weight: 700; color: #111827; }
        .signature-line { border-top: 1px solid #111827; padding-top: 7px; font-size: 10px; color: #5F685F; }
        .report-footer {
            margin-top: 22px; padding-top: 8px; border-top: 1px solid #d1d5db;
            display: flex; justify-content: space-between; gap: 12px; color: #5F685F; font-size: 9.5px;
        }
        .page-number::after { content: counter(page); }
        @media (max-width: 900px) {
            .report-head { grid-template-columns: 1fr; }
            .meta { text-align: left; }
            .summary-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
            .report-title { display: block; }
        }
        @media print {
            body { background: #fff; }
            .sheet { max-width: none; padding: 0; }
            .print-actions { display: none !important; }
            .summary-grid, .filters-block, .signatures { break-inside: avoid; page-break-inside: avoid; }
            thead { display: table-header-group; }
            tfoot { display: table-footer-group; }
            .report-table th,
            .report-table tbody tr:nth-child(even) td,
            .brand-logo,
            .meta,
            .filter { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
</head>
<body>
@php
    $money = fn ($value) => '₱' . number_format((float) $value, 2);
    $number = fn ($value) => number_format((float) $value);
    $columns = [
        'sales' => [
            'case_no' => 'Case No.', 'client' => 'Client', 'deceased' => 'Deceased', 'branch' => 'Branch',
            'package' => 'Package', 'service_type' => 'Service Type', 'total_amount' => 'Total Amount',
            'total_paid' => 'Total Paid', 'balance' => 'Balance', 'payment_status' => 'Payment Status',
            'case_status' => 'Case Status', 'date' => 'Date Created or Paid Date',
        ],
        'master_cases' => [
            'case_no' => 'Case No.', 'case_code' => 'Case Code', 'client' => 'Client', 'deceased' => 'Deceased',
            'branch' => 'Branch', 'service_type' => 'Service Type', 'package' => 'Package', 'interment_date' => 'Interment Date',
            'payment_status' => 'Payment Status', 'case_status' => 'Case Status', 'verification_status' => 'Verification Status',
            'encoded_by' => 'Encoded By', 'date_created' => 'Date Created',
        ],
        'audit_logs' => [
            'date' => 'Date', 'user' => 'User', 'role' => 'Role', 'action' => 'Action', 'action_type' => 'Action Type',
            'module' => 'Module', 'record_id' => 'Record ID', 'branch' => 'Branch', 'status' => 'Status', 'remarks' => 'Remarks',
        ],
        'owner_branch_analytics' => [
            'branch' => 'Branch', 'total_cases' => 'Total Cases', 'paid_cases' => 'Paid Cases', 'partial_cases' => 'Partial Cases',
            'unpaid_cases' => 'Unpaid Cases', 'gross_amount' => 'Gross Amount', 'collected_amount' => 'Collected Amount',
            'remaining_balance' => 'Remaining Balance',
        ],
    ][$reportType] ?? [];
    $moneyColumns = ['total_amount', 'total_paid', 'balance', 'gross_amount', 'collected_amount', 'remaining_balance'];
    $numberColumns = ['total_cases', 'paid_cases', 'partial_cases', 'unpaid_cases'];
    $orderedFilterKeys = ['branch', 'branch_id', 'date_from', 'date_to', 'interment_from', 'interment_to'];
    $orderedFilters = collect($orderedFilterKeys)
        ->filter(fn ($key) => array_key_exists($key, $filters))
        ->mapWithKeys(fn ($key) => [$key => $filters[$key]])
        ->merge(collect($filters)->except($orderedFilterKeys))
        ->all();
@endphp

<main class="sheet">
    <div class="print-actions">
        <button type="button" class="btn" onclick="window.close()">Close</button>
        <button type="button" class="btn btn-primary" onclick="window.print()">Print / Save as PDF</button>
    </div>

    <header class="report-head">
        <div class="brand">
            <div class="brand-logo">
                <img src="{{ asset('images/login-logo.png') }}" alt="Sabangan Caguioa Funeral Home Logo">
            </div>
            <div>
                <h1>Sabangan Caguioa Funeral Home</h1>
                <p>Funeral Home Management System</p>
            </div>
        </div>
        <div class="meta">
            <p><strong>Generated by:</strong> {{ $generatedBy->name ?? 'System User' }}</p>
            <p><strong>Date generated:</strong> {{ $generatedAt->format('Y-m-d H:i') }}</p>
        </div>
    </header>

    <section class="report-title">
        <div>
            <h2>{{ $reportTitle }}</h2>
            <p>Print-ready report generated from the same filters used by the preview page.</p>
        </div>
    </section>

    <section class="filters-block">
        <h3 class="section-label">Selected Filters</h3>
        <div class="filters">
            @forelse($orderedFilters as $label => $value)
                <span class="filter"><strong>{{ \Illuminate\Support\Str::headline($label) }}:</strong> {{ $value }}</span>
            @empty
                <span class="filter">No filters selected</span>
            @endforelse
        </div>
    </section>

    <section class="summary-block">
        <h3 class="section-label">Summary</h3>
        <div class="summary-grid">
            @foreach($summary as $key => $value)
                <article class="summary-card">
                    <span>{{ \Illuminate\Support\Str::headline($key) }}</span>
                    <strong>
                        @if(str_contains($key, 'amount') || str_contains($key, 'balance'))
                            {{ $money($value) }}
                        @else
                            {{ $number($value) }}
                        @endif
                    </strong>
                </article>
            @endforeach
        </div>
    </section>

    <div class="table-wrap">
        <table class="report-table">
            <thead>
                <tr>
                    @foreach($columns as $key => $label)
                        <th class="{{ in_array($key, array_merge($moneyColumns, $numberColumns), true) ? 'number' : '' }}">{{ $label }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @forelse($rows as $row)
                    <tr>
                        @foreach($columns as $key => $label)
                            <td class="{{ in_array($key, array_merge($moneyColumns, $numberColumns), true) ? 'number' : '' }}">
                                @if(in_array($key, $moneyColumns, true))
                                    {{ $money($row[$key] ?? 0) }}
                                @elseif(in_array($key, $numberColumns, true))
                                    {{ $number($row[$key] ?? 0) }}
                                @else
                                    {{ $row[$key] ?? '-' }}
                                @endif
                            </td>
                        @endforeach
                    </tr>
                @empty
                    <tr>
                        <td colspan="{{ max(count($columns), 1) }}" class="empty">No records found based on selected filters.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <section class="signatures">
        <div class="signature-box">
            <div class="signature-label">Prepared by:</div>
            <div class="signature-line">Name and Signature</div>
        </div>
        <div class="signature-box">
            <div class="signature-label">Checked by:</div>
            <div class="signature-line">Name and Signature</div>
        </div>
    </section>

    <footer class="report-footer">
        <span>Generated by Sabangan Caguioa Funeral Home Management System</span>
        <span>Page <span class="page-number"></span></span>
    </footer>
</main>
</body>
</html>
